### ISSUE TITLE
Indentation issues

### ISSUE THREAD

**Issue by svs** [elixir-lang/emacs-elixir#227] opened 2015-07-18 07:04 UTC
I've copy pasted an example from Dave Thomas's Programming Elixir and the indentation is very weird. Example reproduced below:

```elixir
defmodule Issues.CLI do
	@default_count 4
	@moduledoc """
	Handle the command line parsing and the dispatch to
	the various functions that end up generating a
	table of the last _n_ issues in a github project
	"""
	def run(argv) do
		parse_args(argv)
	end
	@doc """
	`argv` can be -h or --help, which returns :help.
	Otherwise it is a github user name, project name, and (optionally)
	the number of entries to format.
	Return a tuple of `{ user, project, count }`, or `:help` if help was given.
	"""
	def parse_args(argv) do
		parse = OptionParser.parse(argv, switches: [ help: :boolean],
															 aliases: [ h: :help ])
		case parse do
			{ [ help: true ], _, _ }
								 -> :help
										{ _, [ user, project, count ], _ }
										-> { user, project, count }
											 { _, [ user, project ], _ }
											 -> { user, project, @default_count }
											 _ -> :help
		end
	end
end
```

I'm using v. 2.2.5 from melpa-stable.

thanks.

**Comment by tonini** [comment] 2015-07-18 07:17
@svs Thanks for reporting. :+1:

**Comment by tonini** [comment] 2015-08-04 19:52
Thanks! Is fixed with #231

**Closed** 2015-08-04 19:52 UTC

**Comment by svs** [comment] 2015-08-22 09:13
```elixir
		case parse do
			{ [ help: true ], _, _ }
				-> :help
			{ _, [ user, project, count ], _ }
				-> { user, project, count }
				{ _, [ user, project ], _ }
				-> { user, project, @default_count }
				_ -> :help
		end
```

the third and fourth cases are improperly implemented.

**Comment by tonini** [comment] 2015-08-22 09:30
I can't reproduce this so far.

I tried the following code and it always indent correct.

```elixir
case parse do
  { [ help: true ], _, _ }
    -> :help
  { _, [ user, project, count ], _ }
    -> { user, project, count }
  { _, [ user, project ], _ }
    -> { user, project, @default_count }
  _ -> :help
end

def asdasd do
  case parse do
    { [ help: true ], _, _ }
      -> :help
    { _, [ user, project, count ], _ }
      -> { user, project, count }
    { _, [ user, project ], _ }
      -> { user, project, @default_count }
    _ -> :help
  end
end
```

What version of `elixir-mode` are you using?

**Comment by svs** [comment] 2015-08-22 12:49
2.2.6

**Comment by tonini** [comment] 2015-08-23 08:53
Ok, I tested it intensively and a few other `elixir-mode` users too and we couldn't reproduce the issue.

I'm wondering if you indent it specific, like go to the line and indent or select the whole block and indent?

I really can't get any issue there.
